add useClipboard hook and add toaster to show clipboard success copy
allejo/json-reshaper pull request #12
Opened 2023-08-19 13:07 UTC by madjed-hue

### Fix change navigator with useClipboard hook
#### Add toaster to show that copy action is triggerd
![Screenshot 2023-08-19 135637](https://github.com/allejo/json-reshaper/assets/62912697/09cf9d04-5625-4999-adfc-7e877d83d18b)
![code](https://github.com/allejo/json-reshaper/assets/62912697/a9ed054e-d1d3-4784-8734-ea049478d73e)

2023-08-20 07:04 UTC, allejo requested changes
Functionality-wise, it's looking good. Thank you!

Just some code changes please

2023-08-20 07:04 UTC, allejo commented on src/components/ToasterProvider.tsx
> +};
Other than future-proofing this in case we want to add more functionality to this component, is there any other benefit? Otherwise, please move the `<Toasted />` call to to App.tsx

2023-08-20 07:04 UTC, allejo commented on src/components/OutputPreview.tsx
>  				console.error(err);
Also display the error in a toast if it fails for some reason

2023-08-20 07:04 UTC, allejo commented on src/components/OutputPreview.tsx
> +	const [value, copy] = useCopyToClipboard();
```suggestion
	const [, copy] = useCopyToClipboard();
```

Since this value isn't being used, it's safe to ignore in the destructuring

2023-08-20 10:37 UTC, madjed-hue commented
Thank you @allejo for your feedback, I did some changes, can you check it, please?

2023-08-21 02:21 UTC, allejo reviewed
This is what I had in mind about moving `<Toaster />` into App.tsx 😄

2023-08-21 02:21 UTC, allejo commented on src/App.tsx
> +			<ToasterProvider />
```suggestion
			<Toaster />
```

2023-08-21 02:21 UTC, allejo commented on src/App.tsx
> +
```suggestion
```

2023-08-21 02:23 UTC, allejo approved these changes

2023-08-21 02:24 UTC, merged