Added the functionality for disabling the copy and download buttons when nothing to preview
allejo/json-reshaper pull request #20
Opened 2023-08-25 08:03 UTC by masterghost2002

## Added the functionality for disabling the copy and download buttons when nothing to preview
## issue
[Issue 8](https://github.com/allejo/json-reshaper/issues/8)

2023-08-30 20:00 UTC, allejo requested changes
Very close! The problem here is that the "Nothing to preview yet!" message shows up when `processed.length <= 1` (the header row counts as 1). Your PR allows for the buttons to show up when there's nothing to preview. I would add a `useEffect` to listen to when `processed` changes and *that's* when `setShowButtons` should be called.

![image](https://github.com/allejo/json-reshaper/assets/1246453/cd79ffd5-a354-4470-a2f4-d2f3a576c1a0)

2023-09-02 09:28 UTC, masterghost2002 commented
Thank you for the guidance sir,
here is a quick view
[Screencast from 2023-09-02 14-55-21.webm](https://github.com/allejo/json-reshaper/assets/55751461/c75793bb-2c13-4c7f-bab6-f2b534490023)

2023-09-03 22:11 UTC, allejo approved these changes
I'm going to merge this PR manually because I made some formatting changes. A few notes for you to take away (in addition to the comments I left below)

1. When you make a PR, never make a PR against your default branch (i.e. `main` or `master`). For example, in this PR you made the PR from `masterghost2002:main` to `allejo:main`; this causes problems like not allowing project maintainers to push to your branch
2. When you make a PR that directly fixes an issue, make sure to use a [closing keyword](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue) so that the PR will automatically mark the issue as completed when it's merged. Example closing keywords are, "fixes," "fixed," "closed," etc.

2023-09-03 22:11 UTC, allejo commented on src/components/TransformDelimiterSeparatedValues.tsx
> +		setShowButtons(()=>processed.length>1);
```suggestion
		setShowButtons(processed.length > 1);
```

I don't believe you need this to be a function call, it'll evaluate to a boolean by itself. It only makes sense to use a function in a state setter if the previous state is needed

2023-09-03 22:11 UTC, allejo commented on src/components/TransformDelimiterSeparatedValues.tsx
> +	setShowButtons:React.Dispatch<React.SetStateAction<boolean>>;
```suggestion
	setShowButtons: StateSetter<boolean>;
```

I have an alias for this type

2023-09-03 22:12 UTC, closed without merging